---
spring:
  datasource:
    url: jdbc:h2:mem:test.db
    username: sa
    password:
    driver-class-name: org.h2.Driver


  h2:
    console:
      enabled: true
      path: /console


  liquibase:
    change-log: classpath:/db/changelog/db.liquibase-diff-changeLog.yaml
